spring:
  application:
    name: dubbo-demo-bff
  profiles:
    active: default

  mvc:
    locale: zh_CN

  redis:
    host: localhost
    port: 6379

  data:
    redis:
      repositories:
        enabled: false

server:
  address: 127.0.0.1
  port: 8080

dubbo:
  registry:
    address: 'multicast://224.5.6.7:23456'
